// import { Inter } from "next/font/google";

import { unstable_setRequestLocale } from "next-intl/server";

// const inter =  Inter({ subsets: ["latin"] });

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  unstable_setRequestLocale(locale);

  return children;
}

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// Add this to enable static generation for all locale variants
