import type { Metadata } from "next";
import localFont from "next/font/local";
import Sidebar from "@/customComponents/dashboardComponent/layout/sidebar";
import Header from "@/customComponents/dashboardComponent/layout/header";
import { getLocale } from "next-intl/server";

const geistSans = localFont({
  src: "../../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  console.log(locale);
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} grid min-h-screen h-full w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr] antialiased font-[family-name:var(--font-geist-sans)]`}
    >
      <Sidebar />
      <div className="flex flex-col">
        <Header />
        <main className="flex flex-1 flex-col gap-4 p-4 lg:gap-6 lg:p-6">
          {children}
        </main>
      </div>
    </div>
  );
}
